[package]
name = "random-algorithms-homework"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["derive"] }
nameof = "1.2.2"
rand = "0.8.5"
